
### MONITORS ###
source = ~/.config/hypr/configs/monitors.conf

### VARIABELS ###
source = ~/.config/hypr/configs/variables.conf

### AUTOSTART ###
source = ~/.config/hypr/configs/autostart.conf

###############
### GENERAL ###
###############

general {
    border_size = 2
    gaps_in = 0
    gaps_out = 0

    col.active_border = rgba(a9a9a9ff)
    col.inactive_border = rgba(d2d2d2ff)

    layout = master
    no_focus_fallback = true
    resize_on_border = true
    allow_tearing = false

    snap {
        enabled = true
        monitor_gap = 15
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    font_family = IBM Plex Sans
}

### DECORATION ###
source = ~/.config/hypr/configs/decoration.conf

### ANIMATIONS ###
source = ~/.config/hypr/configs/animations.conf

### LAYOUT ###
source = ~/.config/hypr/configs/layout.conf

### INPUT ###
source = ~/.config/hypr/configs/input.conf

### KEYBINDINGS ###
source = ~/.config/hypr/configs/binds.conf

### WINDOWRULES ###
source = ~/.config/hypr/configs/windowrules.conf


